### ISSUE TITLE
How to emulate a simple blocking call?

### ISSUE THREAD

**Issue by Animadei** [scriby/asyncblock#30]
I'm trying to re-use an existing asyncblock scope to avoid sprinkling a new scope in every function that needs to call async APIs and to support blocking calls. The module.exports.getCurrentFlow seems to be what I need. Is getCurrentFlow() officially supported?

```
"use strict";

console.log("main start");
console.time("main finish");

let asyncblock = require("asyncblock");

//let optionForceError = true;
let optionForceError = false;

function nonblockingRoutine (done) {
  if (optionForceError)
    setTimeout(() => done(new Error("something bad happened"), "test data"), 1000);
  else
    setTimeout(() => done(null, "test data"), 1000);
}

function blockingRoutine () {
  console.log("    blockingTest 1");
  let flow = asyncblock.getCurrentFlow();
  nonblockingRoutine(flow.add());
  let result = flow.wait();
  console.log("    blockingTest 2");
  return result;
}

asyncblock((flow) => {
  console.log("  enter level 1");
  try {
    let result = blockingRoutine();
    console.log("  result A = " + JSON.stringify(result));
  } catch (e) {
    console.log("  caught exception:", e.stack);
  }
  console.log("  leave level 1");
});

console.timeEnd("main finish");

```

**Comment by scriby** [comment]
You can call asyncblock.getCurrentFlow() to do what you want.

Thanks,

Chris

**Comment by scriby** [comment]
A couple more thoughts on this:

* One drawback of using getCurrentFlow is that callers lose the ability to choose whether to execute a function as blocking or in parallel

* Another drawback is that you can't use it with source transformation (func().sync()), as those have to be nested directly within an asyncblock for the parser to find them.

* In a large application, it would be confusing if some functions auto-blocked and some required a callback. I think you'd want to use it consistently.

* If libraries create their own "threads" by calling setTimeout or after I/O, those "threads" won't have a Fiber attached and the getCurrentFlow call will return null.

For those reasons, when writing code in general I don't use getCurrentFlow. However, in some special circumstances it can create a simpler API. For instance, I use it in https://github.com/scriby/browser-harness quite extensively, as it makes sense to auto-block when doing browser testing.

**Comment by Animadei** [comment]
Can attest that all points are true and I'm OK with their properties in my applications.

In most cases the main work loop will be serial, each incoming message is handled by a switch, and each case calls a blocking function to process the message.

The blocking function can:

1. call aync routines and parallel wait;
2. create a nested asyncblock (no advantage over option 1);
3. parallel wait on WebWorkers (similar to option 1).

The getCurrentFlow() is a core API in my opinion. It enables sequential programming by allowing signal/event primitive to be built and used. Co-routines are here to stay. It's just less overhead than Promises.

Thank you for your response and really appreciate your work.
