### ISSUE TITLE
interactive?

### ISSUE THREAD

**Issue by GianfriAur** [scriby/asyncblock#33]
I'm trying to integrate your module with an interactive solution.

I'm colliding with an error:

```
/home/gianfri/Scrivania/Synthia_0.2/proto2/synthia/bin/lib/asyncblock/asyncblock/lib/flow_fiber.js:26
        this._fiber.run(task);
                    ^

TypeError: Cannot set property '_asyncblock_flow' of null
    at fiberContents (/home/gianfri/Scrivania/Synthia_0.2/proto2/synthia/bin/lib/asyncblock/asyncblock/lib/asyncblock.js:88:32)
```
in the non-interactive version it works perfectly but in the interactive one it gives me this problem

I try to explain how it works

we have an opening process that at a certain point launches 
```
this.synchronizer ((line) => {
   ...
}
```
like` ab(function(flow) { ... }`

at some point I define a context with

```
  this._iVm = require('vm'),
  this._isandbox = require('vm').createContext({
      require: require,
      process:process,
      console: console,
      module:module,
      app: this,
      global:global,
  })
```
then I execute my instruction in my sandbox

`this._iVm.runInContext(this._iteraction.buffer.join("\n"), this._isandbox);`

from the same problem even if I use `require('vm').runInThisContext(...)`

repeat it works correctly until I try to use the module, but only in the interactive version.

some idea?
(I also tried with the normal version 'node -i' and the probema is the same)

**Comment by scriby** [comment]
Would you be able to share a small program that reproduces the problem? It’s a little hard to guess what it could be without seeing all the code.

I’ve never tried asyncblock with vm.createContext, so it’s possible it’s just not compatible.

Thanks,

Chris

**Comment by GianfriAur** [comment]
ok, it's a bit harder to create a small prototype of the error,

I take this opportunity to correct my question. I solved in part, without touching the module:

```
      start() {
            this.synchronizer((line) => {
                this.syncLine = line;
                // ...

                if (this._isInteractive) {
                    // ...
                    this._iLoop(this.syncLine.add("cliexit")); // the callback is called only when the CLI ends
                    this.syncLine.wait("cliexit");
                }

               process.exit();
            });
        }
```

this works, the context is actually open but gives me this error
`Error: yield() called with no fiber running`

this is strange because when it runs in context, fiber is open!

**Comment by GianfriAur** [comment]
here's the code, I'm sorry, it works I'm attaching my test

```
var asyncblock = require("asyncblock")

var _isandbox = require('vm').createContext({
    require: require,
    process:process,
    console: console,
    setTimeout:setTimeout,
    module:module,
    global:global,
})
asyncblock ((line)=>{
    _isandbox.line=line;
    console.time('time');
    console.time('time1');
    console.time('time2');
    console.time('time3');

    process.stdout.write("####  START  ####\n")

    setTimeout(line.add(), 1000);
    line.wait();
    console.timeEnd("time")

    process.stdout.write("####  CECK 1 ####\n")

    setTimeout(line.add(), 2000);
    line.wait(); 
    console.timeEnd("time1")

    process.stdout.write("####  CECK 2 ####\n")

    require('vm').runInContext("setTimeout(line.add(), 3000);",_isandbox);
    line.wait();
    console.timeEnd("time2")

    process.stdout.write("####  CECK 3 ####\n")

    global.line=line;
    require('vm').runInThisContext("setTimeout(line.add(), 3000);");
    line.wait();
    console.timeEnd('time3')

    process.stdout.write("####  CECK 4 ####\n")

    process.stdout.write("####   END   ####\n")
})
```
